name=input("Enter your name:")
fathers=input("Enter your fathers name:")
age=int(input("Enter your age:"))
college=input("Enter your college name:")
branch=input("Eneter your branch:")
roll=int(input("Enter your roll no:"))
phone=int(input("Enter your phone no:"))
print("NAME:",name)
print("FATHERS NAME:",fathers)
print("AGE:",age)
print("COLLEGE:",college)
print("BRANCH:",branch)
print("ROLL NO:",roll)
print("PHONE NO:",phone)